export const REQUEST_BANKS='REQUEST_BANKS';
export const RECEIVE_BANKS_SUCCESS='RECEIVE_BANKS_SUCCESS';
export const RECEIVE_BANKS_ERROR='RECEIVE_BANKS_ERROR';

export const REQUEST_TRANSACTIONS='REQUEST_TRANSACTIONS';
export const RECEIVE_TRANSACTIONS_SUCCESS='RECEIVE_TRANSACTIONS_SUCCESS';
export const RECEIVE_TRANSACTIONS_ERROR='RECEIVE_TRANSACTIONS_ERROR';
export const ADD_TRANSACTION='ADD_TRANSACTION';
export const DELETE_TRANSACTION='DELETE_TRANSACTION';

export const REQUEST_LOGIN='REQUEST_LOGIN';
export const LOGIN_SUCCESS='RECEIVE_LOGIN_SUCCESS';
export const LOGIN_ERROR="RECEIVE_LOGIN_ERROR";
export const LOGOUT='LOGOUT';

export const VIEW_DIALOG='VIEW_DIALOG';
export const HIDE_DIALOG='HIDE_DIALOG';
